-- =============================================================
--  Exam-Prep-Hub : Classes + Student Onboarding schema
--  Run after the base migration (supabase-migration.sql).
--
--  NOTE: This app uses a CUSTOM express-session auth (not Supabase
--  Auth), and the backend talks to Supabase using the SERVICE ROLE
--  key which bypasses RLS. So policies here mirror the existing
--  "allow all" pattern used by profiles/attempts/papers/questions.
--  Authorisation is enforced in backend/src/index.js (e.g. only
--  the teacher who owns a class can approve memberships).
-- =============================================================

-- ----- Classes ---------------------------------------------------------------
CREATE TABLE IF NOT EXISTS classes (
  id            TEXT PRIMARY KEY,                  -- generated by backend (e.g. cls_...)
  code          TEXT NOT NULL UNIQUE,              -- e.g. "6T-M482"
  name          TEXT NOT NULL,                     -- e.g. "6A Maths"
  subject       TEXT,
  class_level   TEXT NOT NULL,                     -- '1' .. '10'
  batch_type    TEXT NOT NULL CHECK (batch_type IN ('toppers','normal')),
  school        TEXT,
  teacher_id    TEXT NOT NULL,                     -- references profiles.id
  teacher_name  TEXT,
  created_at    TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_classes_teacher ON classes (teacher_id);
CREATE INDEX IF NOT EXISTS idx_classes_code    ON classes (upper(code));

-- ----- Memberships (student → class, with approval status) -------------------
CREATE TABLE IF NOT EXISTS memberships (
  id             TEXT PRIMARY KEY,                  -- generated by backend (e.g. mem_...)
  class_id       TEXT NOT NULL REFERENCES classes(id) ON DELETE CASCADE,
  student_id     TEXT NOT NULL,                     -- references profiles.id
  student_name   TEXT NOT NULL,
  roll_number    TEXT NOT NULL,
  parent_phone   TEXT,
  status         TEXT NOT NULL DEFAULT 'pending'
                  CHECK (status IN ('pending','approved','rejected')),
  created_at     TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  decided_at     TIMESTAMPTZ,
  UNIQUE (class_id, student_id)
);

CREATE INDEX IF NOT EXISTS idx_memberships_class   ON memberships (class_id);
CREATE INDEX IF NOT EXISTS idx_memberships_student ON memberships (student_id);
CREATE INDEX IF NOT EXISTS idx_memberships_status  ON memberships (status);

-- ----- Row Level Security (permissive, like the rest of this project) --------
ALTER TABLE classes     ENABLE ROW LEVEL SECURITY;
ALTER TABLE memberships ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Allow all operations on classes" ON classes;
CREATE POLICY "Allow all operations on classes" ON classes FOR ALL USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Allow all operations on memberships" ON memberships;
CREATE POLICY "Allow all operations on memberships" ON memberships FOR ALL USING (true) WITH CHECK (true);

-- =============================================================
--  Done.  Backend generates short join codes like "6T-M482"
--  format: <classLevel><T|N>-<subjInit><3-digit-random>
-- =============================================================
